# Use the official debian image.
image: debian:trixie-slim

test:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y bash bzip2 curl git grep libfontconfig1 procps tar
    - curl https://install.meteor.com/ | sh
    # Since this runs in a Docker container as super user, we need to set the
    # appropriate environment variable to allow Meteor to run as root.
    - export METEOR_ALLOW_SUPERUSER=1
  script:
    - cd meteorapp
    - meteor npm install
    - ./tests.sh
